const fonts = [
  { slug:"babalove", name:"Babalove", idx:"001", tags:["Display"], description:"Babalove is a bold expressive display typeface with playful energy. Its confident letterforms make it ideal for headlines, packaging, and brand identities that demand attention.", styles:[{name:"Thin",weight:"100",file:"Babalove-Thin.otf"},{name:"ExtraLight",weight:"200",file:"Babalove-ExtraLight.otf"},{name:"Light",weight:"300",file:"Babalove-Light.otf"},{name:"Regular",weight:"400",file:"Babalove-Regular.otf"},{name:"Medium",weight:"500",file:"Babalove-Medium.otf"},{name:"SemiBold",weight:"600",file:"Babalove-SemiBold.otf"},{name:"Bold",weight:"700",file:"Babalove-Bold.otf"},{name:"ExtraBold",weight:"800",file:"Babalove-ExtraBold.otf"}], isFamily:true, glyphCount:312, languages:"Latin Extended", opentype:"Ligatures, Alternates", released:"2024", hot:true, folder:"BABALOVE" },
  { slug:"baq-rounded", name:"BAQ Rounded", idx:"002", tags:["Rounded"], description:"BAQ Rounded is a single-weight geometric typeface with softened terminals that give it warmth without sacrificing structure.", styles:[{name:"Regular",weight:"400",file:"BaqRounded.otf"}], isFamily:false, glyphCount:284, languages:"Latin Extended", opentype:"Standard", released:"2024", folder:"BAQ ROUNDED" },
  { slug:"bomkin", name:"Bomkin", idx:"003", tags:["Display"], description:"Bomkin is a display typeface with raw hand-drawn energy. Each letterform carries an expressive weight that works beautifully at large sizes.", styles:[{name:"Light",weight:"300",file:"Bomkin Light.ttf"}], isFamily:false, glyphCount:240, languages:"Latin", opentype:"Standard", released:"2024", folder:"BOMKIN" },
  { slug:"crop", name:"Crop", idx:"004", tags:["Display"], description:"Crop is a geometric display family in Heavy and Light weights each with Upright and Slanted variants. Sharp architectural forms perfect for editorial and poster work.", styles:[{name:"Light Upright",weight:"300",file:"Crop-Light-Upright.otf"},{name:"Light Slanted",weight:"300",file:"Crop-Light-Slanted.otf",oblique:true},{name:"Regular Upright",weight:"400",file:"Crop-Regular-Upright.otf"},{name:"Regular Slanted",weight:"400",file:"Crop-Regular-Slanted.otf",oblique:true},{name:"Heavy Upright",weight:"700",file:"Crop-Heavy-Upright.otf"},{name:"Heavy Slanted",weight:"700",file:"Crop-Heavy-Slanted.otf",oblique:true}], isFamily:true, glyphCount:298, languages:"Latin Extended", opentype:"Standard", released:"2024", folder:"CROP" },
  { slug:"do-it-again", name:"Do It Again", idx:"005", tags:["Handmade"], description:"Do It Again is a single-weight handmade typeface with an authentic gestural quality. Its irregular strokes and natural rhythm bring warmth to any design.", styles:[{name:"Regular",weight:"400",file:"doitagainregular.otf"}], isFamily:false, glyphCount:256, languages:"Latin", opentype:"Standard", released:"2024", hot:true, folder:"Do It Again" },
  { slug:"ebisu", name:"Ebisu", idx:"006", tags:["Japanese"], description:"Ebisu is a Japanese-inspired typeface family spanning Thin through Heavy with matching Oblique variants. Its clean refined construction draws on the precision of Japanese kana design.", styles:[{name:"Thin",weight:"100",file:"Ebisu-Thin.otf"},{name:"Thin Oblique",weight:"100",file:"Ebisu-ThinOblique.otf",oblique:true},{name:"ExtraLight",weight:"200",file:"Ebisu-ExtraLight.otf"},{name:"Light",weight:"300",file:"Ebisu-Light.otf"},{name:"Book",weight:"400",file:"Ebisu-Book.otf"},{name:"Medium",weight:"500",file:"Ebisu-Medium.otf"},{name:"Bold",weight:"700",file:"Ebisu-Bold.otf"},{name:"Heavy",weight:"800",file:"Ebisu-Heavy.otf"},{name:"Black",weight:"900",file:"Ebisu-Black.otf"}], isFamily:true, glyphCount:380, languages:"Latin Extended + Japanese", opentype:"Ligatures, Tabular Figures", released:"2024", folder:"EBISU" },
  { slug:"electro", name:"Electro", idx:"007", tags:["Display"], description:"Electro is a futuristic display typeface built for impact. Its single weight makes a bold statement — perfect for music, tech, and entertainment brands.", styles:[{name:"Regular",weight:"400",file:"Electro.ttf"}], isFamily:false, glyphCount:284, languages:"Latin Extended", opentype:"Standard", released:"2024", folder:"ELECTRO" },
  { slug:"headlined-solid", name:"Headlined Solid", idx:"008", tags:["Display"], description:"Headlined Solid is the high-impact companion to Headlined — its filled forms command attention on posters, covers, and large-format applications.", styles:[{name:"Regular",weight:"400",file:"Headlined Solid.otf"}], isFamily:false, glyphCount:290, languages:"Latin Extended", opentype:"Standard", released:"2024", folder:"HEADLINED SOLID" },
  { slug:"headlined", name:"Headlined", idx:"009", tags:["Display"], description:"Headlined is a powerful editorial display typeface designed for maximum typographic impact. Bold confident forms at headline scale.", styles:[{name:"Regular",weight:"400",file:"Headlined.ttf"}], isFamily:false, glyphCount:290, languages:"Latin Extended", opentype:"Standard", released:"2024", folder:"HEADLINED" },
  { slug:"hiroko", name:"Hiroko", idx:"010", tags:["Japanese"], description:"Hiroko is a refined Japanese-Latin typeface with a distinctive personality. Its carefully balanced strokes bring an elegant cross-cultural sensibility to any project.", styles:[{name:"Regular",weight:"400",file:"Hiroko.otf"}], isFamily:false, glyphCount:520, languages:"Latin + Japanese Kana", opentype:"Standard", released:"2024", hot:true, folder:"HIROKO" },
  { slug:"lippy", name:"Lippy", idx:"011", tags:["Handmade"], description:"Lippy is a playful handmade typeface with expressive letterforms and warm organic character. Versatile for branding, packaging, and editorial use.", styles:[{name:"Regular",weight:"400",file:"Lippy.otf"}], isFamily:false, glyphCount:310, languages:"Latin Extended", opentype:"Standard", released:"2024", folder:"LIPPY" },
  { slug:"miyagi", name:"Miyagi", idx:"012", tags:["Japanese"], description:"Miyagi is a Japanese-inspired display typeface with a distinctly modern sensibility. Its single weight captures a perfect balance between structure and expressiveness.", styles:[{name:"Regular",weight:"400",file:"Miyagi.otf"}], isFamily:false, glyphCount:340, languages:"Latin + Japanese Kana", opentype:"Standard", released:"2024", hot:true, folder:"MIYAGI" },
  { slug:"monino-pro", name:"Monino Pro", idx:"013", tags:["Pro"], description:"Monino Pro is a professional monospaced typeface family spanning Light through Black. Built for code, data, and precision contexts.", styles:[{name:"Light",weight:"300",file:"MoninoPro-Light.ttf"},{name:"Normal",weight:"400",file:"MoninoPro-Normal.ttf"},{name:"Bold",weight:"700",file:"MoninoPro-Bold.ttf"},{name:"Black",weight:"900",file:"MoninoPro-Black.ttf"}], isFamily:true, glyphCount:340, languages:"Latin Extended", opentype:"Tabular Figures, Ligatures", released:"2024", pro:true, folder:"MONINO PRO" },
  { slug:"monolite", name:"Monolite", idx:"014", tags:["Display"], description:"Monolite is a single-weight display typeface with a clean architectural presence. Its geometric precision makes it ideal for modern branding and interface design.", styles:[{name:"Regular",weight:"400",file:"Monolite.otf"}], isFamily:false, glyphCount:280, languages:"Latin Extended", opentype:"Standard", released:"2024", folder:"MONOLITE" },
  { slug:"nanami", name:"Nanami", idx:"015", tags:["Japanese"], description:"Nanami is a Japanese-inspired geometric sans-serif. Drawing on the clean grid systems of Japanese kana design, it brings structural precision to Latin letterforms — engineered and warm in equal measure.", styles:[{name:"ExtraLight",weight:"200",file:"Nanami-ExtraLight.otf"},{name:"ExtraLight Oblique",weight:"200",file:"Nanami-ExtraLightOblique.otf",oblique:true},{name:"Book",weight:"300",file:"Nanami-Book.otf"},{name:"Book Oblique",weight:"300",file:"Nanami-BookOblique.otf",oblique:true},{name:"Bold",weight:"700",file:"Nanami-Bold.otf"},{name:"Bold Oblique",weight:"700",file:"Nanami-BoldOblique.otf",oblique:true},{name:"Heavy",weight:"800",file:"Nanami-Heavy.otf"},{name:"Black",weight:"900",file:"Nanami-Black.otf"},{name:"Black Oblique",weight:"900",file:"Nanami-BlackOblique.otf",oblique:true}], isFamily:true, glyphCount:347, languages:"Latin Extended", opentype:"Ligatures, Alternates, Tabular Figures", released:"2024", folder:"NANAMI" },
  { slug:"nanami-handmade", name:"Nanami Handmade", idx:"016", tags:["Handmade"], description:"Nanami Handmade reimagines the Nanami family with hand-drawn warmth. Each weight carries the structural DNA of Nanami while introducing an organic human touch.", styles:[{name:"ExtraLight",weight:"200",file:"Nanami-HM-ExtraLight.otf"},{name:"Light",weight:"300",file:"Nanami-HM-Light.otf"},{name:"Book",weight:"400",file:"Nanami-HM-Book.otf"},{name:"Medium",weight:"500",file:"Nanami-HM-Medium.otf"},{name:"Bold",weight:"700",file:"Nanami-HM-Bold.otf"},{name:"Heavy",weight:"800",file:"Nanami-HM-Heavy.otf"},{name:"Black",weight:"900",file:"Nanami-HM-Black.otf"}], isFamily:true, glyphCount:320, languages:"Latin Extended", opentype:"Standard", released:"2024", folder:"NANAMI HANDMADE" },
  { slug:"nanami-pro", name:"Nanami Pro", idx:"017", tags:["Japanese Pro"], description:"Nanami Pro is the extended professional edition adding Outline and Inline variants alongside the full weight range. Maximum versatility for demanding projects.", styles:[{name:"Thin",weight:"100",file:"Nanami-Thin.otf"},{name:"Thin Oblique",weight:"100",file:"Nanami-ThinOblique.otf",oblique:true},{name:"Light",weight:"300",file:"Nanami-Light.otf"},{name:"Light Oblique",weight:"300",file:"Nanami-LightOblique.otf",oblique:true},{name:"Medium",weight:"500",file:"Nanami-Medium.otf"},{name:"Medium Oblique",weight:"500",file:"Nanami-MediumOblique.otf",oblique:true},{name:"Inline",weight:"400",file:"NanamiInline.otf"},{name:"Outline Regular",weight:"400",file:"NanamiOutline-Regular.otf"},{name:"Outline Oblique",weight:"400",file:"NanamiOutline-Oblique.otf",oblique:true}], isFamily:true, glyphCount:347, languages:"Latin Extended", opentype:"Ligatures, Alternates, Tabular Figures", released:"2024", pro:true, folder:"NANAMI PRO" },
  { slug:"nanami-rounded-pro", name:"Nanami Rounded Pro", idx:"018", tags:["Rounded Pro"], description:"Nanami Rounded Pro softens geometric precision with carefully rounded terminals — friendly and approachable without losing the family's architectural integrity.", styles:[{name:"Thin",weight:"100",file:"Nanami Rounded Pro Thin.otf"},{name:"ExtraLight",weight:"200",file:"Nanami Rounded Pro Extra Light.otf"},{name:"Light",weight:"300",file:"Nanami Rounded Pro Light.otf"},{name:"Normal",weight:"400",file:"Nanami Rounded Pro Normal.otf"},{name:"Medium",weight:"500",file:"Nanami Rounded Pro Medium.otf"},{name:"Bold",weight:"700",file:"Nanami Rounded Pro Bold.otf"},{name:"Heavy",weight:"800",file:"Nanami Rounded Pro Heavy.otf"},{name:"Black",weight:"900",file:"Nanami Rounded Pro Black.otf"}], isFamily:true, glyphCount:340, languages:"Latin Extended", opentype:"Ligatures, Alternates", released:"2024", pro:true, hot:true, folder:"NANAMI ROUNDED PRO", longDescription:"Over 3,000 trusted users... Nanami Rounded Pro is the heavily engineered follow up to the hugely successful Nanami and Nanami Rounded font families. Nanami Rounded Pro contains all the wonder of the original Nanami families, but with vastly extended language support including Cyrillic and Extended Latin, leading to a total of 458 carefully crafted glyphs. The original Nanami Rounded was a key font in many a typography collection, but with these new multi-lingual credentials, Nanami Rounded Pro has become a true must-have font for anyone who's serious about design." },
  { slug:"nerolina", name:"Nerolina", idx:"019", tags:["Display"], description:"Nerolina is a bold single-weight display typeface with a strong editorial presence. Its distinctive forms make it memorable at any size.", styles:[{name:"Regular",weight:"400",file:"NEROLINIA.ttf"}], isFamily:false, glyphCount:276, languages:"Latin Extended", opentype:"Standard", released:"2024", folder:"NEROLINIA" },
  { slug:"rika", name:"Rika", idx:"020", tags:["Japanese"], description:"Rika is a refined Japanese-Latin display typeface with delicate precise construction. Elegant and restrained — ideal for luxury and editorial applications.", styles:[{name:"Regular",weight:"400",file:"Rika.otf"}], isFamily:false, glyphCount:290, languages:"Latin + Japanese Kana", opentype:"Standard", released:"2024", folder:"RIKA" },
  { slug:"roka", name:"Roka", idx:"021", tags:["Display"], description:"Roka is an expressive display typeface with a strong visual character. Its bold distinctive forms are built for headlines, posters, and brand identities that need to stand out.", styles:[{name:"Regular",weight:"400",file:"Roka.otf"}], isFamily:false, glyphCount:310, languages:"Latin Extended", opentype:"Standard", released:"2024", folder:"ROKA" },
  { slug:"shine-pro", name:"Shine Pro", idx:"022", tags:["Pro"], description:"Shine Pro is a professional display family in Regular and Bold weights each with matching Oblique variants. Polished high-contrast forms for premium brand work.", styles:[{name:"Regular",weight:"400",file:"Shine-Pro-Regular.otf"},{name:"Regular Oblique",weight:"400",file:"Shine-Pro-Reg-Oblique.otf",oblique:true},{name:"Bold",weight:"700",file:"Shine-Pro-Bold.otf"},{name:"Bold Oblique",weight:"700",file:"Shine-Pro-Bold-Oblique.otf",oblique:true}], isFamily:true, glyphCount:320, languages:"Latin Extended", opentype:"Ligatures, Alternates", released:"2024", pro:true, folder:"SHINE PRO" },
  { slug:"sobek", name:"Sobek", idx:"023", tags:["Display"], description:"Sobek is a bold single-weight display typeface inspired by ancient Egyptian design. Its powerful geometric forms bring authority and presence to any headline application.", styles:[{name:"Regular",weight:"400",file:"Sobek.ttf"}], isFamily:false, glyphCount:268, languages:"Latin Extended", opentype:"Standard", released:"2024", folder:"SOBEK" },
  { slug:"vow-neue", name:"Vow Neue", idx:"024", tags:["Display"], description:"Vow Neue is a refined single-weight display typeface with a contemporary sensibility. Clean, confident, and versatile — equally strong in editorial and brand contexts.", styles:[{name:"Regular",weight:"400",file:"Vow-Neue.otf"}], isFamily:false, glyphCount:290, languages:"Latin Extended", opentype:"Standard", released:"2024", hot:true, folder:"VOW NEUE" },
  { slug:"york-handwriting", name:"York Handwriting", idx:"025", tags:["Handmade"], description:"York Handwriting is an authentic handwritten typeface with natural flow and genuine character. Its organic letterforms bring a personal human touch to any design.", styles:[{name:"Regular",weight:"400",file:"YorkHandwriting.ttf"}], isFamily:false, glyphCount:280, languages:"Latin Extended", opentype:"Standard", released:"2024", folder:"YORK HANDWRITING" },
  { slug:"yuki", name:"Yuki", idx:"026", tags:["Japanese"], description:"Yuki is a Japanese-inspired typeface family in Regular and Bold weights each with Lined variants. Clean structured forms with a distinctly East Asian typographic influence.", styles:[{name:"Regular",weight:"400",file:"Yuki.ttf"},{name:"Bold",weight:"700",file:"YukiBold.ttf"},{name:"Lined",weight:"400",file:"YukiLined.ttf"},{name:"Lined Bold",weight:"700",file:"YukiLinedBold.ttf"}], isFamily:true, glyphCount:310, languages:"Latin + Japanese Kana", opentype:"Standard", released:"2024", folder:"YUKI" },
  { slug:"yume", name:"Yume", idx:"027", tags:["Japanese"], description:"Yume is a Japanese-Latin typeface with an elegant dreamlike quality. Its single weight strikes a perfect balance between Eastern typographic tradition and contemporary Western design.", styles:[{name:"Regular",weight:"400",file:"Yoko.otf"}], isFamily:false, glyphCount:350, languages:"Latin + Japanese Kana", opentype:"Standard", released:"2024", folder:"YOKO" },
  { slug:"yumo", name:"Yumo", idx:"028", tags:["Japanese"], description:"Yumo is a large-scale Japanese-Latin typeface with over 2500 glyphs spanning Latin Extended, Hiragana, Katakana, and CJK characters.", styles:[{name:"Regular",weight:"400",file:"Yuko.ttf"}], isFamily:false, glyphCount:2584, languages:"Latin + Japanese (Full)", opentype:"CJK Support", released:"2024", folder:"YUKO" },
];

const pricing = {
  single: { desktop:{label:"Desktop",price:25,desc:"Up to 5 CPUs"}, web:{label:"Web",price:35,desc:"250k pageviews/mo"}, app:{label:"App",price:55,desc:"Single application"}, broadcast:{label:"Broadcast",price:85,desc:"TV · Film · Streaming"}, bundle:{label:"Full Bundle",price:130,desc:"All licenses"} },
  family: { desktop:{label:"Desktop",price:45,desc:"Up to 5 CPUs"}, web:{label:"Web",price:65,desc:"250k pageviews/mo"}, app:{label:"App",price:95,desc:"Single application"}, broadcast:{label:"Broadcast",price:145,desc:"TV · Film · Streaming"}, bundle:{label:"Full Bundle",price:220,desc:"All licenses"} },
};

export { fonts, pricing };
export default fonts;
